# Generated by Django 4.0.6 on 2023-07-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='userid',
            field=models.IntegerField(null=True),
        ),
    ]
