# Generated by Django 4.0.6 on 2023-07-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_detallepedido_userid_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['id'], 'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='pedidos',
        ),
    ]
