# Generated by Django 4.0.6 on 2023-07-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedido_options_alter_pedido_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='cant',
            field=models.IntegerField(default=1),
        ),
    ]
