# Generated by Django 4.0.6 on 2023-07-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_detallepedido_cant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'ordering': ['id'], 'verbose_name': 'detalle', 'verbose_name_plural': 'detalles'},
        ),
        migrations.AlterModelTable(
            name='detallepedido',
            table='detalles',
        ),
    ]
