# Generated by Django 4.0.6 on 2023-06-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasUsuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombreUsuario',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
