# Generated by Django 4.0.6 on 2023-06-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasUsuario', '0002_cliente_nombreusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='contraseña',
            new_name='contrasenia',
        ),
    ]
