# Generated by Django 4.0.6 on 2023-07-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentasUsuario', '0003_rename_contraseña_cliente_contrasenia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
