# Generated by Django 4.0.6 on 2023-07-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name': 'marcas'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
